------------------------------------------------------------------------



CREATE TABLE SUMO_TIPOSIGNAL (
    IDTIPOSIGNAL NUMBER(10) PRIMARY KEY,
    DESCRIPCION VARCHAR2(100)
);

INSERT INTO SUMO_TIPOSIGNAL VALUES (1, 'SEMÁFORO');
INSERT INTO SUMO_TIPOSIGNAL VALUES (2, 'PARE');
INSERT INTO SUMO_TIPOSIGNAL VALUES (3, 'CEDA EL PASO');

CREATE TABLE SUMO_CARRERA (
    IDCARRERA NUMBER(10) PRIMARY KEY,
    DESCRIPCION VARCHAR(100),
    SENTIDO VARCHAR2(100)
);

INSERT INTO SUMO_CARRERA VALUES (1, 'CARRERA 100', 'NORTE - SUR');

CREATE TABLE SUMO_CALLE (
    IDCALLE NUMBER(10) PRIMARY KEY,
    DESCRIPCION VARCHAR(100),
    SENTIDO VARCHAR2(100)
);

INSERT INTO SUMO_CALLE VALUES (1, 'CALLE 16', 'ORIENTE - OCCIDENTE');
INSERT INTO SUMO_CALLE VALUES (2, 'CALLE 16', 'OCCIDENTE - ORIENTE');

CREATE TABLE SUMO_TIPOVEHICULO (
    IDTIPOVEHICULO NUMBER(10) PRIMARY KEY,
    DESCRIPCION VARCHAR(100)
);

INSERT INTO SUMO_TIPOVEHICULO VALUES (1, 'CARRO');
INSERT INTO SUMO_TIPOVEHICULO VALUES (2, 'MOTO');


CREATE TABLE SUMO_VEHICULO (
    IDVEHICULO NUMBER(10) PRIMARY KEY,
    DESCRIPCION VARCHAR(100),
    CANTIDAD NUMBER(10),
    IDTIPOVEHICULO NUMBER(10)
);

INSERT INTO SUMO_VEHICULO VALUES (1, '', 10, 1);
INSERT INTO SUMO_VEHICULO VALUES (2, '', 20, 2);

ALTER TABLE SUMO_VEHICULO
ADD CONSTRAINT FK_VEHICULO_TIPOVEHICULO
FOREIGN KEY (IDTIPOVEHICULO) REFERENCES SUMO_TIPOVEHICULO(IDTIPOVEHICULO);

CREATE TABLE SUMO_INTERSECCION (
    IDINTERSECCION NUMBER(10) PRIMARY KEY,
    IDCARRERA NUMBER(10),
    IDCALLE NUMBER(10),
    IDVEHICULO NUMBER(10),
    IDTIPOSIGNAL NUMBER(10)
);

ALTER TABLE SUMO_INTERSECCION
ADD CONSTRAINT FK_INTERSECCION_CARRERA
FOREIGN KEY (IDCARRERA) REFERENCES SUMO_CARRERA(IDCARRERA);

ALTER TABLE SUMO_INTERSECCION
ADD CONSTRAINT FK_INTERSECCION_CALLE
FOREIGN KEY (IDCALLE) REFERENCES SUMO_CALLE(IDCALLE);

ALTER TABLE SUMO_INTERSECCION
ADD CONSTRAINT FK_INTERSECCION_VEHICULO
FOREIGN KEY (IDVEHICULO) REFERENCES SUMO_VEHICULO(IDVEHICULO);

ALTER TABLE SUMO_INTERSECCION
ADD CONSTRAINT FK_INTERSECCION_TIPOSIGNAL
FOREIGN KEY (IDTIPOSIGNAL) REFERENCES SUMO_TIPOSIGNAL(IDTIPOSIGNAL);

INSERT INTO SUMO_INTERSECCION VALUES (1, 1, 1, 2, 1);
INSERT INTO SUMO_INTERSECCION VALUES (2, 1, 2, 1, 1);


SELECT SI.IDINTERSECCION, SCRA.DESCRIPCION, SCRA.SENTIDO, SC.DESCRIPCION, SC.SENTIDO, SV.CANTIDAD, ST.DESCRIPCION 
FROM SUMO_INTERSECCION SI
INNER JOIN SUMO_CARRERA SCRA ON SCRA.IDCARRERA = SI.IDCARRERA
INNER JOIN SUMO_CALLE SC ON SC.IDCALLE = SI.IDCALLE
INNER JOIN SUMO_VEHICULO SV ON SV.IDVEHICULO = SI.IDVEHICULO
INNER JOIN SUMO_TIPOSIGNAL ST ON ST.IDTIPOSIGNAL = SI.IDTIPOSIGNAL


